services:
  mariadb:
    extends:
      service: mariadb
      file: compose.yml
    restart: always
  api:
    extends:
      service: api
      file: compose.yml
    build:
      target: prod
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - /logs:/logs

volumes:
  db-data:

networks:
  db-be-network:
